geekcard/urls.py
#coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .api import router


admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/', include(router.urls)),
    #url(r'^account/$', 'account.views.show_my_profile'),  # redirect do własnego profilu? nieee...
    url(r'^account/', include('registration.backends.default.urls')),
    # player/ -> lista graczy
    # player/[login]/ -> profil gracza
    # league/ -> strona ze zbiorczymi wynikami lig, dany gracz podświetlony
    url(r'^league/', include('league.urls.league', namespace='league')),
    url(r'^league-utils/', include('league.urls.utils', namespace='league_utils')),
    url(r'^player/', include('league.urls.player', namespace='player')),
    url(r'^rental/', include('lending.urls', namespace='lending')),
    # league/[game]/ -> konkretna liga (gra)
    # league/[game]/[slug]/ -> sezon w danej grze
    # url(r'^select2/', include('select2.urls')),
    url(r'^select2/', include('django_select2.urls')),
    # url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^collector/', include('collector.urls', namespace='collector')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lending/urls.py
#coding: utf-8

from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import LendGameView, LendItemView  #, ResolveLendView

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='lending/item_list.html'), name='index'),
    # url(r'^game/$', RedirectView.as_view(url=reverse_lazy('item:index'))),
    url(r'^game/(?P<pk>[\d]+)/$', LendGameView.as_view(), name='game_detail'),
    # url(r'^games/$', RedirectView.as_view(url=reverse_lazy('item:index'))),
    url(r'item/$', RedirectView.as_view(url=reverse_lazy('lending:index')), name='item_list'),
    url(r'items/$', RedirectView.as_view(url=reverse_lazy('lending:index'))),
    url(r'^item/(?P<pk>[\d]+)/$', LendItemView.as_view(), name='item_detail'),
    # url(r'^make_it_so/$', ResolveLendView.as_view(), name='make_it_so'),
    url(r'^make_it_so/$', 'lending.views.resolve_lend', name='make_it_so'),
)

lending/models.py
#coding: utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.utils.timezone import now
from django_extensions.db.fields import ShortUUIDField
from account.models import Player
from django.db.models import Max, Avg, Min, Sum, Count
import datetime
from .dyncat import categories
import logging
# import select2.fields

from decimal import Decimal

logger = logging.getLogger('dev_debug')


class GameCategory(models.Model):
    uuid = ShortUUIDField()
    name = models.CharField(max_length=64)
    parser = models.CharField(max_length=200, choices=categories.choices(), null=True, blank=True)

    def __unicode__(self):
        return self.name

    def __init__(self, *args, **kwargs):
        super(GameCategory, self).__init__(*args, **kwargs)
        self._handler = self.get_price_handler()

    def get_price_handler(self):
        return categories.get(self.parser, None)


class GameCategoryOption(models.Model):
    uuid = ShortUUIDField()
    days = models.PositiveSmallIntegerField(default=1)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=1)
    value = models.DecimalField(max_digits=5, decimal_places=2, default=1)
    category = models.ForeignKey(GameCategory)

    def __unicode__(self):
        return _("%(days)s dni  - %(price)s zł") % {'days': self.days, 'price': self.price}

    def get_price_for_item(self, item):
        try:
            return self.category._handler.get_price(item=item, option=self)
        except Exception as e:
            logger.error("Error %s: %s" % (type(e), e))
            return Decimal("%.2f" % self.price)


class GameToLend(models.Model):
    uuid = ShortUUIDField()
    name = models.CharField(max_length=256)
    desc = models.TextField(blank=True)
    ean = models.CharField(max_length=13, blank=True)
    category = models.ForeignKey(GameCategory)
    full_price = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    pic = models.ImageField(upload_to='lending/', blank=True)
    shop_url = models.URLField(help_text=_('Link do sklepu.'), blank=True)
    # related = models.ManyToManyField('GameToLend')  # trzeba by zadbać o to, by linkowanie było obustronne

    def __unicode__(self):
        return self.name

    def get_ratings(self):
        return self.ratings.filter(value__gte=0).aggregate(value=Avg('value'))['value']


class ReturnedItemsManager(models.Manager):
    def get_queryset(self):
        qs = super(ReturnedItemsManager, self).get_queryset()
        return qs.exclude(pk__in=Item.objects.filter(lendit__returned__isnull=True, lendit__isnull=False))


class Item(models.Model):
    """
    Konkretny egzemplarz gry
    """
    # game = models.ForeignKey(GameToLend)
    uuid = ShortUUIDField()
    game = models.ForeignKey(GameToLend)
    barcode = models.CharField(max_length=13, unique=True)
    borrowers = models.ManyToManyField(Player, through='LendIt', related_name='borrowed_items')
    # borrowers = select2.fields.ManyToManyField(Player, through='LendIt', ajax=True,
    #                                            related_name='borrowed_items', sort_field='when')
    objects = models.Manager()
    returned = ReturnedItemsManager()

    # przydałby się atrybut mówiący o tym, czy dany egzemplarz jest na stanie

    class Meta:
        ordering = ['game__name', 'barcode']

    @property
    def available(self):
        return self.lendit_set.filter(returned__isnull=True).count() == 0

    @property
    def reserved(self):
        return self.cartitem_set.filter(reserved=True).count() != 0

    def return_it(self):
        """
        Zwrot pożyczonej gry. Zwraca liczbę dni opóźnienia i cenę.
        """
        # TODO: poprawić obliczanie kwoty karnej - trzeba wyszukać domyślną cenę lub pobrać najmniejszą dla tej kategorii
        try:
            obj = LendIt.objects.get(item=self, returned__isnull=True)
            obj.returned = now()
            late = (obj.returned - obj.when).days - obj.days  # fix issue #4
            obj.late = late
            obj.save()
            if late > 0:
                price = GameCategoryOption.objects.filter(category=self.game.category).order_by('days', 'price')[0].price
                return late, late * price
            else:
                return 0, 0
        except LendIt.DoesNotExist:
            return 0, 0

    def __unicode__(self):
        return "%s %s" % (self.game.name, self.barcode)

    @property
    def when_will_be_back(self):
        lendit = self.lendit_set.filter(returned__isnull=True)
        if lendit.count():
            try:
                days = lendit[0].option.days
            except:
                days = lendit[0].days
            return lendit[0].when.date() + datetime.timedelta(days=days)
        return None

    @property
    def overdue(self):
        lendit = self.lendit_set.filter(returned__isnull=True)
        if lendit.count():
            try:
                days = lendit[0].option.days
            except:
                days = lendit[0].days
            od = (now() - lendit[0].when).days - days
            return od
        return None

    @property
    def lagger(self):
        lendit = self.lendit_set.filter(returned__isnull=True)
        if lendit:
            return lendit[0].person
        else:
            return None


class GameRating(models.Model):
    uuid = ShortUUIDField()
    person = models.ForeignKey(Player)
    game = models.ForeignKey(GameToLend, related_name='ratings')
    value = models.DecimalField(max_digits=2, decimal_places=1, default=-1)
    desc = models.TextField(blank=True)
    when = models.DateTimeField(auto_now=True)


class LendIt(models.Model):
    uuid = ShortUUIDField()
    item = models.ForeignKey(Item)
    person = models.ForeignKey(Player)
    option = models.ForeignKey(GameCategoryOption, help_text=_('Opcja wypożyczenia - na ile i za ile.'), null=True, blank=True, editable=False)  # DEPRECATED!
    days = models.PositiveSmallIntegerField(_('Ile dni'))
    # TODO: ograniczyć dostępność opcji cenowych w panelu admina
    when = models.DateTimeField(auto_now_add=True)
    returned = models.DateTimeField(null=True, blank=True,
                                    help_text=_('DATA ZWROTU. Data wypożyczenia dodawana jest automatycznie.'))
    late = models.SmallIntegerField(_('late'), default=0, editable=False)

    class Meta:
        ordering = ['-when']


class Cart(models.Model):
    uuid = ShortUUIDField()
    owner = models.ForeignKey(Player)
    items = models.ManyToManyField(Item, through='CartItem')

    def add_item(self, item):
        self.items.add(item)


class CartItem(models.Model):
    uuid = ShortUUIDField()
    item = models.ForeignKey(Item)
    cart = models.ForeignKey(Cart)
    added = models.DateTimeField(auto_now_add=True)
    reserved = models.BooleanField(default=False)

lending/forms.py
# coding: utf-8
__author__ = 'minder'

from django.forms import ModelForm, Form
from django.forms.models import inlineformset_factory

from .models import Item, LendIt, Player, GameCategoryOption
# from select2.fields import MultipleChoiceField, ForeignKey, ModelChoiceField, ManyToManyField

from django_select2 import AutoModelSelect2MultipleField, ModelSelect2Field, AutoModelSelect2Field
from .utils import as_choices


# ################# FIELDS #################
#
# class MultiItemsField(AutoModelSelect2MultipleField):
#     queryset = Item.returned
#     search_fields = ['game__name__icontains', 'barcode__contains']
#
#
class PlayerS2Field(AutoModelSelect2Field):
    queryset = Player.objects
    search_fields = ['first_name__icontains', 'last_name__icontains', 'club_cards__barcode__contains']

#
# ################# FORMS #################
#

class LendingForm(ModelForm):
    # item = select2.fields.ForeignKey(Item)
    person = PlayerS2Field()

    class Meta:
        model = LendIt

    # def __init__(self, *args, **kwargs):
    #     if 'item' in kwargs:
    #         item = kwargs.pop('item')
    #     else:
    #         item = None
    #     super(LendingForm, self).__init__(*args, **kwargs)
    #     if item is not None:
    #         self.fields['option'].queryset = GameCategoryOption.objects.filter(category=item.game.category)


class ReturnForm(ModelForm):
    class Meta:
        model = LendIt

#
# class MultiLendingForm(Form):
#     # items = MultipleChoiceField(choices=Item.returned.as_choices())
#     # items = django_select2.fields.HeavySelect2MultipleChoiceField(choices=Item.returned.as_choices())
#     items = MultiItemsField()
#
#
# class LendToPersonForm(ModelForm):
#     class Meta:
#         model = Player
#         fields = ['id']


LendItInlineFormSet = inlineformset_factory(Player, LendIt, fields=['item', 'days'], extra=1)

lending/templates/lending/cart_list.html
{% extends 'base.html' %}{% load lending_tags %}

{% block content %}
    <h3>Rezerwacje użytkowników</h3>
<ul>
    {% for cart in object_list|remove_empty_carts %}
    <li><a href="{% url 'player:show_cart' cart.owner.username %}">{{ cart.owner.get_full_name }}</a> (pozycji: {{ cart.items.count }})</li>
    {% empty %}
        Brak koszyków
{% endfor %}
</ul>
{% endblock %}

lending/templates/lending/game_detail.html
{% extends 'base.html' %}

{% block content %}
    {{ object.name }} - szczegóły wkrótce

{% endblock %}

lending/templates/lending/item_detail.html
{% extends 'base.html' %}{% load lending_tags league_tags %}

{% block content %}
    <div class="col-md-5">
    <h2>{{ object.game.name }}</h2> szczegóły gry wkrótce
    </div>
    {% lending_form %}
    {% if user.is_staff %}
        <div class="col-md-10">
        <h4>Ostatnie wypożyczenia</h4>
        <table class="table table-striped">
            <tr><th>Osoba</th><th>Wypożyczenie</th><th>Zwrot</th><th>Dekl. dni</th></tr>
            {% for l in object.lendit_set.all|slice:":5" %}
            <tr><td>{% link_user l.person %}</td><td>{{ l.when }}</td><td>{{ l.returned }}</td><td>{{ l.days }}</td></tr>
        {% endfor %}</table>
        </div>

    {% endif %}
{% endblock %}

lending/templates/lending/item_list.html
{% extends 'base.html' %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.11/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.11/angular-cookies.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.11/angular-resource.js"></script>
    <script src="{{ STATIC_URL }}js/libs/ui-bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/app/games_list.js"></script>
{% endblock %}
{% load fontawesome_tags %}
{% block content %}
    <div ng-app="KlubStrefy" class="container">

        <h3>Gry dostępne w wypożyczalni</h3>

        <div class="row">
            <div class="col-md-4">
                <input class="form-control" placeholder="Wyszukaj..." ng-model="searchGames" autofocus>
            </div>
            {#            <div class="col-md-8">&nbsp;</div>#}
        </div>
        <div ng-controller="ListCtrl" >

            <div ng-show="list_loading"><i class="fa fa-refresh fa-spin"></i></div>
            <table  class="table table-hover col-md-12" ng-hide="list_loading">
                <thead>
                <tr>
                    <th>Dost.</th>
                    <th>Tytuł</th>
                    <th>Kod</th>
                    <th>Kiedy zwrot</th>
                    <th>Przetrzymano</th>
                    <th>Osoba</th>
                    {% if user.is_staff %}<th>Zwrot</th> <th>Do koszyka</th>{% endif %}
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="item in items | filter:searchGames">
                    <td><span ng-if="item.available == true"
                              class="text-success">{% fa_icon 'check' 'Dostępna' %}</span>
                        <span ng-if="item.available == false"
                              class="text-danger">{% fa_icon 'times' 'Niedostępna' %}</span></td>
                    <td><a href="{$ item.link $}">{$ item.game.name $}</a></td>
                    <td><a href="{$ item.link $}">{$ item.barcode $}</a></td>
                    <td>{$ item.when_will_be_back $}</td>
                    <td>{$ item.overdue $}</td>
                    <td><a href="{$ item.lagger_link $}" ng-if="item.lagger_link">{$ item.lagger_name $}</a></td>
                    {% if user.is_staff %}
                        <td>
                            <form method='post'
                                  action="{% url 'lending:make_it_so' %}?next={% firstof request.path '/' %}"
                                  ng-hide="item.available">
                                {% csrf_token %}
                                <input type="hidden" name="item" value="{$ item.id $}">
                                <input type="hidden" name="action" value="return">
                                <button class="btn btn-xs btn-danger">Zwrot</button>
                            </form>
                        </td>
                        <td>
                            <form method='post'
                                  action="{% url 'lending:make_it_so' %}?next={% firstof request.path '/' %}">
                                {% csrf_token %}
                                <input type="hidden" name="item" value="{$ item.id $}">
                                <input type="hidden" name="action" value="add_to_cart">
                                <button class="btn btn-xs btn-success" ng-show="item.available && !item.reserved">Rezerwacja</button>
                                <button class="btn btn-xs btn-warning" ng-hide="item.available">Przedłużenie</button>
                                <button class="btn btn-xs btn-danger" ng-show="item.reserved" disabled>Rezerwacja</button>
                            </form>
                        </td>
                    {% endif %}
                </tr>
            </tbody>
            </table>
        </div>
    </div>

{% endblock %}

lending/templates/lending/multi_lendit.html
{% load lending_tags fontawesome_tags bootstrap3 league_tags %}

lending/templates/lending/navbar.html
{% load fontawesome_tags %}<a href="{% url 'lending:index' %}">{% fa_icon 'cubes' %} Wypożyczalnia</a>

lending/templates/lending/personal_lend.html
{% extends 'base.html' %}{% load avatar_tags bootstrap3 league_tags fontawesome_tags lending_tags %}

{% block content %}
<form method="post" class="form col-md-6" action="{% url 'player:personal_lend' slug=player.username %}">
    {% csrf_token %}
    {% bootstrap_formset formset %}
{% buttons %}
    <button type="submit" class="btn">Zapisz</button>
{% endbuttons %}
</form>
{% endblock %}

lending/templates/lending/show_cart.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ cart.owner.get_full_name }} - koszyk</h3>
    {% if cart.items.count %}
    <form method="post" role="form" class="col-md-4 col-md-offset-4 table-responsive">
    {% csrf_token %}{% if user.is_staff %}<label>Ososba: </label> {{ form.person }}{% endif %}
        <table class="table table-hover table-condensed">
            <thead>
            <tr>
                <th>#</th>
                <th>Tytuł</th>
                <th>Ile dni</th>
                <th>Usuń</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart.items.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.game.name }}</td>
                    <td><input class="form-control input-sm" type="number" name="item-days:{{ item.id }}" value="1"></td>
                    <td><input class="form-control input-sm" type="checkbox" name="item-del:{{ item.id }}"></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-info" name="action" value="save" >Zapisz</button>
        <button type="submit" class="btn btn-danger" name="action" value="empty">Usuń zawartość</button>

    </form>
    {% else %}
    Koszyk jest pusty
    {% endif %}
{% endblock %}

lending/templates/lending/tag_lending_current.html
{% if items %}
<table class="table table-striped">
<tr><th>Tytuł</th><th>Wydano</th><th>Na ile dni</th>
    {% if user.is_staff or user.is_superuser %}<th>
        <form method="post" action="{% url 'lending:make_it_so' %}?next={% firstof request.path '/' %}">{% csrf_token %}
            <input type="hidden" name="action" value="return_all">
            <input type="hidden" name="player" value="{{ player.username }}">
            <button class="btn btn-xs btn-danger">Zwróć wszystkie</button></form></th>{% endif %}</tr>
    {% for item in items %}{% with item.item.overdue as overdue %}
    <tr{% if overdue == 0 %} class="warning"{% elif overdue > 0 %} class="danger"{% endif %}><td>{{ item.item.game.name }}</td><td>{{ item.when }}</td><td>{{ item.days }}</td>
        {% if user.is_staff or user.is_superuser %}<td>
            <form method='post' action="{% url 'lending:make_it_so' %}?next={% firstof request.path '/' %}">
                {% csrf_token %}
                <input type="hidden" name="item" value="{{ item.item_id }}">
                <input type="hidden" name="action" value="return">
                <button class="btn btn-xs btn-info">Zwrot</button>
            </form>
        </td>{% endif %}</tr>{% endwith %}
{% endfor %}</table>
{% else %}
    Brak aktualnie wypożyczonych gier
{% endif %}

lending/templates/lending/tag_lending_form.html
{% load lending_tags fontawesome_tags bootstrap3 league_tags %}
{% if is_away %}
    <div>
    Wypożyczony{% if user.is_authenticated %} przez: {% link_user lender %}{% endif %}
    </div>
    <div>Przewidywana data zwrotu: {{ item.when_will_be_back }}</div>
    {% if user.is_staff or user == lender %}<div>{% with item.overdue as od %}{% if od > 0 %}Przetrzymano: {{ od }} {{ od|pluralize:'dzień,dni' }}{% endif %}{% endwith %}</div>{% endif %}
{% endif %}
{% if user.is_superuser %}
    <form action="{% url 'lending:make_it_so' %}" method="post" class="form col-md-4">
        {% csrf_token %}
        {% if is_away %}
            <h3>Zwrot do wypożyczalni</h3>
            <input type="hidden" name="action" value="return">
            <input type="hidden" name="item" value="{{ item.id }}">
            {% buttons %}
                <button type="submit" class="btn btn-primary">Zwrot</button>
            {% endbuttons %}
        {% else %}
            <h3>Wypożyczanie</h3>
            <input type="hidden" name="item" value="{{ item.id }}">
            {% bootstrap_field form.person %}
            {% bootstrap_field form.days %}
            <input type="hidden" name="action" value="lend">
            {% buttons %}
                <button type="submit" class="btn btn-primary">Wypożycz</button>
            {% endbuttons %}
        {% endif %}
    </form>
    <div class="col-md-2">
        <h5>Opcje wypożyczenia:</h5>
        {% regroup item.game.category.gamecategoryoption_set.all by days as option_list %}
    <ul>{% for opt in option_list %}
        <li>{{ opt.list.0.days }} {{ opt.list.0.days|pluralize:"dzień,dni"}}: {{ opt.list.0.price }} zł</li>{% endfor %}
    </ul>
    </div>
{% endif %}

lending/templates/lending/tag_lending_history.html
{% if items %}
<table class="table table-striped">
<tr><th>Tytuł</th><th>Wydano</th><th>Zwrot</th><th>Przetrz.</th></tr>
    {% for item in items %}
    <tr{% if item.late > 0 %} class="danger"{% endif %}><td>{{ item.item.game.name }}</td><td>{{ item.when }}</td><td>{{ item.returned }}</td><td>{{ item.late }}</td></tr>
{% endfor %}</table>
{% else %}
    Brak historii wypożyczonych gier
{% endif %}

lending/templates/lending/tag_multilending_form.html
{% load lending_tags fontawesome_tags bootstrap3 league_tags %}
{% if user.is_superuser or user.is_staff %}
    <form action="{% url 'lending:make_it_so' %}" method="post" class="form col-md-4">
    {% csrf_token %}
{#    <h3>Wypożyczanie</h3>#}
{#    <input type="hidden" name="person" value="{{ lender.pk }}">#}
{#    <input type="hidden" name="action" value="multilend">#}
{#    {{ form.as_p }}#}
{#    {% buttons %}#}
{#        <button type="submit" class="btn btn-primary">Wypożycz</button>#}
{#    {% endbuttons %}#}
    {{ form.as_p }}
    {% for form in inline %}
        {% bootstrap_form form %}
    {% endfor %}


    </form>
{% endif %}

lending/templates/lending/tag_rental_report.html
{% if items %}
    <h3>Aktualnie wypożyczone</h3>{% load bootstrap3 %}{% load fontawesome_tags %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Tytuł</th>
            <th>Wypożyczono</th>
            <th>Kiedy zwrot</th>
            <th>Przetrzymano</th>
            <th>Osoba</th>
            <th>Zwrot</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            {% with item.item.overdue as overdue %}
                <tr{% if overdue > 0 %} class="bg-danger"{% elif overdue == 0 %} class="bg-warning"{% endif %}>
                    <td><a href="{% url 'lending:item_detail' item.item_id %}">{{ item.item.game.name }}</a></td>
                    <td>{{ item.when }}</td>
                    <td>{{ item.item.when_will_be_back }}</td>
                    <td>{{ item.item.overdue }}</td>
                    <td><a href="{% url 'player:detail' item.person.username %}">{{ item.person.get_full_name }}</a></td>
                    <td>
                        <form method='post'
                              action="{% url 'lending:make_it_so' %}?next={% firstof request.path '/' %}">
                            {% csrf_token %}
                            <input type="hidden" name="item" value="{{ item.item.id }}">
                            <input type="hidden" name="action" value="return">
                            <button class="btn btn-xs btn-danger">Zwrot</button>
                        </form>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>
{% endif %}